# === Раздел с общими конфигурационными параметрами ===
runtime:
  symbols: [ "BTC_USDT", "ETH_USDT", "USDD_USDT", "TRX_USDT", "BTT_USDT", "NFT_USDT", "XRP_USDT",
             "ETH_BTC", "XRP_BTC", "TRX_BTC", "LTC_BTC", "EOS_BTC", "XMR_BTC", "DOGE_BTC",
             "NFT_TRX", "ETH_TRX", "JST_TRX", "XRP_TRX",
             "ETHBULL_USDT", "BULL_USDT", "BEAR_USDT", "ADABULL_USDT" ]

  updateTimeout: 45
  errorTimeout: 10

orderbook:
  levels: [ 0.0, 0.2, 0.4, 0.6, 0.8,
            1.0, 1.2, 1.4, 1.6, 1.8,
            2.0, 2.2, 2.4, 2.6, 2.8,
            3.0, 3.3, 3.6, 3.9,
            4.2, 4.5, 4.8,
            5.1, 5.4, 5.7, 100 ]

trades:
  depth: 86400

# === Database params ===
db:
  #host: 185.117.118.107
  host: 127.0.0.1
  port: 59000
  database: rt5


# === Логирование ===
log:
  version: 1
  disable_existing_loggers: False

  formatters:
    standard:
      format: '%(asctime)s %(name)30s [%(levelname)8s]: %(message)s'
    telegram:
      format: '%(message)s'

  handlers:
    console:
      level: DEBUG
      formatter: standard
      class: logging.StreamHandler
      stream: ext://sys.stdout  # Default is stderr

    file:
      level: DEBUG
      formatter: standard
      class: logging.handlers.RotatingFileHandler
      filename: logs/log.log
      mode: a
      maxBytes: 500000
      backupCount: 15

    telegram:
      level: CRITICAL
      formatter: telegram
      class: logging_telegram_handler.TelegramHandler
      chat_id: 211945135
      alias: "PDC"


# -- Логгеры --
  loggers:
    '':
      handlers: [console, file]
      level: ERROR
      propagate: False

    __main__:
      handlers: [console, file, telegram]
      level: WARNING
      propagate: False

    basic_application:
      handlers: [console, file, telegram]
      level: DEBUG

    config_manager:
      level: INFO

      log_manager:
        level: INFO

      poloniex.public:
        level: ERROR

      controllers.abstract:
        level: ERROR

      controllers.trades:
        level: ERROR

      controllers.orderbook:
        level: ERROR

      clickhouse_connector.clickhouse_connector:
        level: ERROR